CREATE OR REPLACE PACKAGE PK_GESTION_CLIENTES AS
    TIPO_CLIENTE_EXCEP          EXCEPTION;
    CLIENTE_BAJA_EXCEP          EXCEPTION;
    CLIENTE_CUENTAS_EXCEP       EXCEPTION;
    JURIDICA_INEXISTENTE_EXCEP  EXCEPTION;
    AUTORIZACION_INVALIDA_EXCEP EXCEPTION;
    
    PROCEDURE ALTA_CLIENTE(IDENT IN CLIENTE.IDENT%TYPE,
                            TIPO_CLIENTE IN CLIENTE.TIPO_CLIENTE%TYPE, ESTADO IN CLIENTE.ESTADO%TYPE,
                            FECHA_ALTA IN CLIENTE.FECHA_ALTA%TYPE, FECHA_BAJA IN CLIENTE.FECHA_BAJA%TYPE,
                            DIRECCION IN CLIENTE.DIRECCION%TYPE, CIUDAD IN CLIENTE.CIUDAD%TYPE, 
                            CODIGO_POSTAL IN CLIENTE.CODIGO_POSTAL%TYPE, PAIS IN CLIENTE.PAIS%TYPE,
                            RAZON_SOCIAL IN EMPRESA.RAZON_SOCIAL%TYPE, 
                            NOMBRE IN INDIVIDUAL.NOMBRE%TYPE, APELLIDO IN INDIVIDUAL.APELLIDO%TYPE, FECHA_NACIMIENTO IN INDIVIDUAL.FECHA_NACIMIENTO%TYPE);
    PROCEDURE MODIFICAR_CLIENTE(IDENTIDAD IN CLIENTE.IDENT%TYPE, EST IN CLIENTE.ESTADO%TYPE,
                                FB IN CLIENTE.FECHA_BAJA%TYPE, DIR IN CLIENTE.DIRECCION%TYPE,
                                CIUD IN CLIENTE.CIUDAD%TYPE,  CP IN CLIENTE.CODIGO_POSTAL%TYPE,
                                P IN CLIENTE.PAIS%TYPE);
    PROCEDURE BAJA_CLIENTE(IDENTIDAD IN CLIENTE.IDENT%TYPE, FB IN CLIENTE.FECHA_BAJA%TYPE);
    PROCEDURE ALTA_AUTORIZADO(ID_JURIDICA IN CLIENTE.ID%TYPE, TIPO_AUTORIZ IN AUTORIZACION.TIPO%TYPE,
                                IDENTIDAD IN PERS_AUTORIZ.IDENT%TYPE,
                                NOM IN PERS_AUTORIZ.NOMBRE%TYPE, APEL IN PERS_AUTORIZ.APELLIDO%TYPE,
                                DIR IN PERS_AUTORIZ.DIRECCION%TYPE, FECH_NAC IN PERS_AUTORIZ.FECHA_NACIMIENTO%TYPE,
                                FECH_INIC IN PERS_AUTORIZ.FECHA_INICIO%TYPE, FECH_FIN IN PERS_AUTORIZ.FECHA_FIN%TYPE);
    PROCEDURE MODIFICAR_AUTORIZADO(ID_JURIDICA IN CLIENTE.ID%TYPE, ID_AUTORIZADA IN PERS_AUTORIZ.ID%TYPE, 
                                    TIPO_AUTORIZ IN AUTORIZACION.TIPO%TYPE, NOM IN PERS_AUTORIZ.NOMBRE%TYPE,
                                    APEL IN PERS_AUTORIZ.APELLIDO%TYPE, DIR IN PERS_AUTORIZ.DIRECCION%TYPE, 
                                    FECH_NAC IN PERS_AUTORIZ.FECHA_NACIMIENTO%TYPE, ESTAD IN PERS_AUTORIZ.ESTADO%TYPE,
                                    FECH_INIC IN PERS_AUTORIZ.FECHA_INICIO%TYPE, FECH_FIN IN PERS_AUTORIZ.FECHA_FIN%TYPE);
    PROCEDURE ELIMINAR_AUTORIZADOS(ID_JURIDICA IN EMPRESA.ID%TYPE);
END PK_GESTION_CLIENTES;