CREATE OR REPLACE PACKAGE PK_GESTION_CUENTAS AS
    CLIENTE_INEXISTENTE_EXCEP   EXCEPTION;
    CLIENTE_DADO_BAJA_EXCEP     EXCEPTION;
    CTA_REF_YA_EXISTE_EXCEP     EXCEPTION;
    NO_HAY_CUENTAS_EXCEP        EXCEPTION;
    SALDO_MAYOR_CERO_EXCEP      EXCEPTION;

    PROCEDURE APERTURA_CUENTA(ID_CLIENTE IN CLIENTE.ID%TYPE, IBAN_CUENTA IN CUENTA.IBAN%TYPE,
                                SWIFT_CUENTA IN CUENTA.SWIFT%TYPE,
                                FECHA_APERTURA_FINTECH IN CTA_FINTECH.FECHA_APERTURA%TYPE, FECHA_CIERRE_FINTECH IN CTA_FINTECH.FECHA_CIERRE%TYPE,
                                CLASIFICACION_FINTECH IN CTA_FINTECH.CLASIFICACION%TYPE, COMISION_SEGREGADA IN SEGREGADA.COMISION%TYPE,
                                IBAN_REF IN CUENTA.IBAN%TYPE, SWIFT_REF IN CUENTA.SWIFT%TYPE,
                                NOMBRE_BANCO_REF IN CTA_REF.NOMBRE_BANCO%TYPE, SUCURSAL_REF IN CTA_REF.SUCURSAL%TYPE,
                                PAIS_REF IN CTA_REF.PAIS%TYPE, SALDO_REF IN CTA_REF.SALDO%TYPE,
                                FECHA_APERTURA_REF IN CTA_REF.FECHA_APERTURA%TYPE, DIVISA_REF IN CTA_REF.DIVISA_ABREV%TYPE);
    PROCEDURE CIERRE_CUENTA(IBAN_CUENTA IN CUENTA.IBAN%TYPE);
END PK_GESTION_CUENTAS;