CREATE OR REPLACE PACKAGE PK_OPERATIVA AS
    PROCEDURE INSERTAR_TRANSACCION(ID_TRANS IN TRANSACCION.ID%TYPE,
                                    FECHA_INST IN TRANSACCION.FECHA_INSTRUCCION%TYPE, CANTIDAD_TRANS IN TRANSACCION.CANTIDAD%TYPE,
                                    FECHA_EJEC IN TRANSACCION.FECHA_EJECUCION%TYPE, TIPO_TRANS IN TRANSACCION.TIPO%TYPE,
                                    COMISION_TRANS IN TRANSACCION.COMISION%TYPE, INTERNACIONAL_TRANS IN TRANSACCION.INTERNACIONAL%TYPE,
                                    DIVISA_ORIGEN IN TRANSACCION.DIVISA_ABREV_ORIGEN%TYPE, DIVISA_DESTINO IN TRANSACCION.DIVISA_ABREV_DESTINO%TYPE,
                                    IBAN_ORIGEN IN TRANSACCION.CUENTA_IBAN_ORIGEN%TYPE, IBAN_DESTINO IN TRANSACCION.CUENTA_IBAN_DESTINO%TYPE);
    PROCEDURE CAMBIO_DIVISA(IBAN_ORIGEN IN TRANSACCION.CUENTA_IBAN_ORIGEN%TYPE, IBAN_DESTINO IN TRANSACCION.CUENTA_IBAN_DESTINO%TYPE,
                            DIVISA_ORIGEN IN TRANSACCION.DIVISA_ABREV_ORIGEN%TYPE, DIVISA_DESTINO IN TRANSACCION.DIVISA_ABREV_DESTINO%TYPE);
END PK_OPERATIVA;