CREATE OR REPLACE PACKAGE PK_OPERATIVA AS
    PROCEDURE INSERTAR_TRANSACCION(FECHA_INST TRANSACCION.FECHA_INSTRUCCION%TYPE, CANTIDAD_TRANS TRANSACCION.CANTIDAD%TYPE,
                                    FECHA_EJEC TRANSACCION.FECHA_EJECUCION%TYPE, TIPO_TRANS TRANSACCION.TIPO%TYPE,
                                    COMISION_TRANS TRANSACCION.COMISION%TYPE, INTERNACIONAL_TRANS TRANSACCION.INTERNACIONAL%TYPE,
                                    DIVISA_ORIGEN TRANSACCION.DIVISA_ABREV_ORIGEN%TYPE, DIVISA_DESTINO TRANSACCION.DIVISA_ABREV_DESTINO%TYPE,
                                    IBAN_ORIGEN TRANSACCION.CUENTA_IBAN_ORIGEN%TYPE, IBAN_DESTINO TRANSACCION.CUENTA_IBAN_DESTINO%TYPE);
    PROCEDURE CAMBIO_DIVISA(IBAN_ORIGEN TRANSACCION.CUENTA_IBAN_ORIGEN%TYPE, IBAN_DESTINO TRANSACCION.CUENTA_IBAN_DESTINO%TYPE,
                            DIVISA_ORIGEN TRANSACCION.DIVISA_ABREV_ORIGEN%TYPE, DIVISA_DESTINO TRANSACCION.DIVISA_ABREV_DESTINO%TYPE);
END PK_OPERATIVA;